### ISSUE TITLE
Issue with Nested Schemas in OpenAPI generator

### ISSUE THREAD

**Issue by 0sssama** [fuma-nama/fumadocs#642]
### To Reproduce

1. Create a `test.yaml` with the following content
```yaml
openapi: 3.0.3
info:
  title: Test API
  version: 0.0.1
paths:
  /v1/get-folder:
    get:
      tags: []
      summary: Get Folder
      operationId: GetFolder
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Folder'
  /v1/get-relation:
    get:
      tags: []
      summary: Get Relation Definition
      operationId: GetRelationDefinition
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationDefinition'
components:
  schemas:
    RelationDefinition:
      type: object
      properties:
        name:
          type: string
          description: Name of the relation definition
        definition:
          $ref: '#/components/schemas/Folder'
    Folder:
      type: object
      properties:
        file:
          type: string
        folders:
          type: array
          items:
            $ref: '#/components/schemas/Folder'
```

2. Load the file to FumaDocs' `generateFiles` OpenAPI generator in a `scripts/generate-docs.mjs` file

```js
import { generateFiles } from 'fumadocs-openapi';

void generateFiles({
  input: ['openapi/test.yaml'],
  output: '/content/api',
  per: 'operation',
})
```

3. run the script, you should get the following error:

```
/Users/some-project/node_modules/lodash/lodash.js:10612
      var memoized = function() {
                             ^

RangeError: Maximum call stack size exceeded
    at memoized (/Users/some-project/node_modules/lodash/lodash.js:10612:30)
    at /Users/some-project/node_modules/json-schema-to-typescript/dist/src/generator.js:256:104
    at Array.map (<anonymous>)
    at generateInterface (/Users/some-project/node_modules/json-schema-to-typescript/dist/src/generator.js:256:14)
    at generateRawType (/Users/some-project/node_modules/json-schema-to-typescript/dist/src/generator.js:151:20)
    at generateTypeUnmemoized (/Users/some-project/node_modules/json-schema-to-typescript/dist/src/generator.js:128:18)
    at memoized (/Users/some-project/node_modules/lodash/lodash.js:10620:27)
    at /Users/some-project/node_modules/json-schema-to-typescript/dist/src/generator.js:145:55
    at generateRawType (/Users/some-project/node_modules/json-schema-to-typescript/dist/src/generator.js:147:15)
    at generateTypeUnmemoized (/Users/some-project/node_modules/json-schema-to-typescript/dist/src/generator.js:128:18)

Node.js v18.18.0
```

### Current vs. Expected behavior

Current behavior: Error!

Expected behavior: generation of a docs page from the OpenAPI file

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.22
  pnpm: 8.12.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

UI

**Comment by fuma-nama** [comment]
Looks like an upstream problem from https://github.com/bcherny/json-schema-to-typescript/issues/482

I'll add an option to disable it as a temporarily fix
