### ISSUE TITLE
Manifest.json is an empty array

### ISSUE THREAD

**Issue by Skreeauk** [fuma-nama/fumadocs#825]
### To Reproduce

Static Export

1. npm run build
2. out folder is completed, tries to [MDX] writing manifest
3. it fails

### Current vs. Expected behavior

Expected manifest.json to have something but its just an empty array

### Provide environment information

```bash
OS: Windows 11 23H2

Binaries:

node: 20.17.0
npm: 10.8.2

Relevant Packages:

"fumadocs-core": 13.4.7
"fumadocs-mdx": 10.0.1
"fumadocs-ui": 13.4.7
"next": 14.2.8
"react": 18.3.1
"react-dom": 18.3.1

Next.js Config:

output: "export",
eslint: {
	ignoreDuringBuilds: true,
},
images: {
	unoptimized: true,
}
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

Works just fine on run dev, only error in build

error for one mdx:
```
[MDX] writing manifest
cannot find the search index of D:/Projects/NodeJS/dark-gbf/content/docs/celeste/changelog.mdx Error: ENOENT: no such file or directory, open 'D:\Projects\NodeJS\dark-gbf\.next\cache\fumadocs\f8aa6ffdd452107adddfdbb6d532bd68d3a4c96e367a79005bedf60448cbc3c7.json'
    at Object.openSync (node:fs:573:18)
    at Object.readFileSync (node:fs:452:35)
    at writeManifest (file:///D:/Projects/NodeJS/dark-gbf/node_modules/fumadocs-mdx/dist/chunk-P6WKCOD5.mjs:116:27)
    at process.<anonymous> (file:///D:/Projects/NodeJS/dark-gbf/node_modules/fumadocs-mdx/dist/next/index.mjs:161:7)        
    at process.emit (node:events:519:28)
    at process.processEmit [as emit] (D:\Projects\NodeJS\dark-gbf\node_modules\next\dist\compiled\ora\index.js:1:59071)     
    at process.exit (node:internal/process/per_thread:185:15)
    at D:\Projects\NodeJS\dark-gbf\node_modules\next\dist\bin\next:80:99
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\Projects\\NodeJS\\dark-gbf\\.next\\cache\\fumadocs\\f8aa6ffdd452107adddfdbb6d532bd68d3a4c96e367a79005bedf60448cbc3c7.json'
}
```

source.config.ts
```jsx
import {
	defineDocs,
	defineConfig,
	frontmatterSchema,
} from "fumadocs-mdx/config"

import { z } from "zod"

export const { docs, meta } = defineDocs({
	docs: {
		schema: frontmatterSchema.extend({
			keywords: z.array(z.string()).default([]),
			wikiURL: z.string().default(""),
		}),
	},
})

export default defineConfig({
	generateManifest: true,
})
```

source.js
```jsx
import { docs, meta } from "@/.source"
import { createMDXSource } from "fumadocs-mdx"
import { loader } from "fumadocs-core/source"
import { Icons, createIcon } from "@/components/Icon"

export const source = loader({
	baseUrl: "/docs",
	icon(icon) {
		if (icon && icon in Icons) return createIcon({ icon: Icons[icon] })
	},
	source: createMDXSource(docs, meta),
})
```

generated source.config.mjs in .source
```mjs
// source.config.ts
import {
  defineDocs,
  defineConfig,
  frontmatterSchema
} from "fumadocs-mdx/config";
import { z } from "zod";
var { docs, meta } = defineDocs({
  docs: {
    schema: frontmatterSchema.extend({
      keywords: z.array(z.string()).default([]),
      wikiURL: z.string().default("")
    })
  }
});
var source_config_default = defineConfig({
  generateManifest: true
});
export {
  source_config_default as default,
  docs,
  meta
};
```

**Comment by fuma-nama** [comment]
Could you provide a minimal reproduction?
Is there a cache folder to be generated?

**Comment by Skreeauk** [comment]
https://github.com/user-attachments/assets/ada07b3c-222f-4e3e-a29e-e52c0a0a3443

Checking the file its trying to open (starts with 6c69be...), there is no such file in .next/cache/fumadocs as seen in the video

I think the best I could do is provide a github repo? I'm not sure if this is a windows thing or something else

**Comment by Skreeauk** [comment]
![image](https://github.com/user-attachments/assets/333ddd77-8eca-4f2b-a793-32d153463583)

Works just fine on code sandbox

Link to the repo: https://github.com/Skreeauk/fumadoc-mdx10

**Comment by fuma-nama** [comment]
Weird, it means it's likely a windows issue. Will test on my Windows PC later

**Comment by fuma-nama** [comment]
Yes it's because of some inconsistencies of file paths between Webpack and our Manifest generator, a fix is coming

**Comment by Skreeauk** [comment]
Not sure if the fault lies here, but from what I see,

Its using filePath as the hash key when generating the cache files
```ts
await fs2.writeFile(
        path3.resolve(".next/cache/fumadocs", `${getKey(filePath)}.json`),
        JSON.stringify({
          path: filePath,
          data: file.data
        })
      );
```

While the reading part is using the whole file as the key?
```ts
function writeManifest(to, config) {
  const output = { files: [] };
  for (const [file, collection] of config._runtime.files.entries()) {
    const type = config.collections.get(collection)?.type ?? getTypeFromPath(file);
    if (type === "meta") continue;
    try {
      const content = fs2.readFileSync(
        path2.resolve(".next/cache/fumadocs", `${getKey(file)}.json`)
      );
      const meta = JSON.parse(content.toString());
      output.files.push({
        ...meta,
        collection
      });
    } catch (e) {
      console.error(`cannot find the search index of ${file}`, e);
    }
  }
  fs2.writeFileSync(to, JSON.stringify(output));
}
```

**Comment by fuma-nama** [comment]
no, it's because of backslash and forward slash

**Comment by fuma-nama** [comment]
If the problem still occurs, please notify me
