### ISSUE TITLE
CLI - `system error -8`

### ISSUE THREAD

**Issue by limegorilla** [fuma-nama/fumadocs#959]
### To Reproduce

Run one of the CLI commands (e.g `pnpx fumadocs config / init`)

Immediate Error

### Current vs. Expected behavior

```
pnpm: Command failed with Unknown system error -8: fumadocs config
spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:762:9)
    at execa (/Users/liamdoyle/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:19996:32)
    at default_1 (/Users/liamdoyle/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:20224:38)
    at Object.handler [as dlx] (/Users/liamdoyle/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:224948:35)
    at async /Users/liamdoyle/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:234540:21
    at async main (/Users/liamdoyle/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:234499:34)
    at async runPnpm (/Users/liamdoyle/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:234770:5)
    at async /Users/liamdoyle/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:234762:7
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020
  Available memory (MB): 65536
  Available CPU cores: 24
Binaries:
  Node: 20.18.0
  npm: 10.8.2
  Yarn: 4.4.0
  pnpm: 9.12.1
Relevant Packages:
  next: 15.0.0 // Latest available version is detected (15.0.0).
  eslint-config-next: N/A
  react: 19.0.0-rc-cd22717c-20241013
  react-dom: 19.0.0-rc-cd22717c-20241013
  typescript: 5.6.2
Next.js Config:
  output: N/A
```
```


### Which area(s) are affected? (Select all that apply)

CLI (create-fumadocs-app)

### Additional context

_No response_

**Comment by fuma-nama** [comment]
Does pnpm dlx and npx work?

**Comment by limegorilla** [comment]
This is me trying to run `pnpm dlx` / `npx`

**Comment by fuma-nama** [comment]
Checked it again on CodeSandbox, it should be working now. Please notify me if the issue still occurs.
